services:


  ollama:

    build:
      context: ./ollama

    container_name: rag-ollama

    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    networks:
      - rag-network

  postgres:
    image: postgres:16
    container_name: rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./postgres/data:/var/lib/postgresql/data

    healthcheck:

        test:
          [
            "CMD-SHELL",
            "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
          ]

        interval: 5s

        timeout: 5s

        retries: 10  

    networks:
      - rag-network


  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    restart: unless-stopped

    ports:
      - "6333:6333"

    volumes:
      - ./qdrant/storage:/qdrant/storage

    networks:
      - rag-network



  redis:
    image: redis:7
    container_name: rag-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - rag-network



  rabbitmq:

    image: rabbitmq:3-management

    container_name: rag-rabbitmq

    restart: unless-stopped

    environment:

      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}

      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


    ports:

      - "5672:5672"
      - "15672:15672"

    healthcheck:

        test:
          [
            "CMD",
            "rabbitmq-diagnostics",
            "ping"
          ]

        interval: 10s

        timeout: 5s

        retries: 10

    networks:

      - rag-network



  # api:

  #   build:
  #     context: ./api


  #   container_name: rag-api

  #   restart: unless-stopped


  #   ports:
  #     - "${API_PORT}:8000"


  #   depends_on:

  #     - postgres
  #     - qdrant
  #     - redis


  #   env_file:
  #     - .env


  #   networks:
  #     - rag-network



  ingestion:

    build:
      context: ./ingestion


    container_name: rag-ingestion

    restart: unless-stopped


    volumes:

      - ./docs:/app/docs


    env_file:

      - .env

    depends_on:

      postgres:

        condition: service_healthy

      rabbitmq:

        condition: service_started  


    networks:

      - rag-network



  embedding:

    env_file:

      - .env

    build:
      context: ./embedding


    container_name: rag-embedding


    restart: unless-stopped


    depends_on:

      rabbitmq:

        condition: service_healthy


      qdrant:

        condition: service_started


    networks:

      - rag-network



  frontend:

    build:

      context: ./frontend


    container_name: rag-frontend


    ports:

      - "${FRONTEND_PORT}:3000"


    depends_on:

      - rag-api


    networks:

      - rag-network
  rag-api:

    build:
      context: ./rag-api


    container_name: rag-api


    restart: unless-stopped


    ports:

      - "8000:8000"


    depends_on:

      - qdrant


    networks:

      - rag-network

volumes:

  ollama_data:

networks:

  rag-network:

    driver: bridge